sáb 28 dez 2024 20:40:04 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -3,8 +3,8 @@
 # shellcheck shell=bash disable=SC1091,SC2039,SC2166
 #
 #  pkgbuild.install
-#  Created: 2024/12/05 - 10:03
-#  Altered: 2024/12/05 - 10:03
+#  Created: 2024/12/23 - 21:12
+#  Altered: 2024/12/23 - 21:12
 #
 #  Copyright (c) 2024-2024, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
@@ -29,65 +29,156 @@
 #  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 #  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ##############################################################################
-# Installation file for Arch Linux packages
-# This file contains scripts that are executed at different stages of package installation/upgrade/removal
 
 # Function executed before package installation
-# pre_install() {
-#     echo "Preparing to install the package..."
-# Example: Check for system dependencies
-# if ! command -v required_command &> /dev/null; then
-#     echo "Error: required_command not found. Please install it before continuing."
-#     exit 1
-# fi
-# }
+pre_install() {
+  echo "Preparing to install gnome-professional-theme"
+}
 
 # Function executed after package installation
-# post_install() {
-#     echo "Configuring the package after installation..."
-# Example: Create a configuration directory
-# mkdir -p /etc/mypackage
-# chmod 755 /etc/mypackage
+post_install() {
+	echo "Applying gnome-professional-theme GNOME and configuring GTK..."
 
-# Example: Start a service
-# systemctl enable myservice.service
-# systemctl start myservice.service
-# }
+	# Get the username of the user running the package installation
+	user=$(logname)
+	user_home=$(getent passwd "$user" | cut -d: -f6)
 
-# Function executed before package upgrade
-# pre_upgrade() {
-#     echo "Preparing to upgrade the package..."
-# Example: Backup configuration files
-# cp /etc/mypackage/config.conf /etc/mypackage/config.conf.bak
-# }
+	if [ -z "$user_home" ]; then
+		echo "Could not determine the home directory for user $user. Skipping theme application."
+		return
+	fi
 
-# Function executed after package upgrade
-# post_upgrade() {
-#     echo "Finalizing package upgrade..."
-# Usually, post_install is called here to ensure
-# all post-installation configurations are applied
-#     post_install
+	# Directories
+	GTK4_DIR="$user_home/.config/gtk-4.0"
+	GTK3_DIR="$user_home/.config/gtk-3.0"
+	THEMES_DIR="/usr/share/themes"
+	BACKUP_DIR="$user_home/backup_customizations"
 
-# Example: Check and update configuration files
-# if [ -f /etc/mypackage/config.conf.pacnew ]; then
-#     echo "New configuration file available. Please review /etc/mypackage/config.conf.pacnew"
-# fi
-# }
+	# Backup function
+	backup_directory() {
+		local dir="$1"
+		local backup_path="$BACKUP_DIR/$(basename "$dir")-$(date +%Y%m%d%H%M%S).tar.gz"
+
+		mkdir -p "$BACKUP_DIR"
+		if [ -d "$dir" ]; then
+			echo "Backing up $dir to $backup_path"
+			tar -czf "$backup_path" -C "$(dirname "$dir")" "$(basename "$dir")"
+		else
+			echo "Directory $dir does not exist. Skipping backup."
+		fi
+	}
+
+	# Backup and update GTK 4 configuration
+	if [ -d "$GTK4_DIR" ]; then
+		echo "Directory $GTK4_DIR already exists. Backing up..."
+		backup_directory "$GTK4_DIR"
+	else
+		echo "Directory $GTK4_DIR not found. Creating..."
+		mkdir -p "$GTK4_DIR"
+	fi
+	cp -rp $THEMES_DIR/Tokyonight-Dark-Theme/gtk-4.0/* "$GTK4_DIR/"
+
+	# Backup and update GTK 3 configuration
+	if [ -d "$GTK3_DIR" ]; then
+		echo "Directory $GTK3_DIR already exists. Backing up..."
+		backup_directory "$GTK3_DIR"
+	else
+		echo "Directory $GTK3_DIR not found. Creating..."
+		mkdir -p "$GTK3_DIR"
+	fi
+	cp -rp $THEMES_DIR/Tokyonight-Dark-Theme/gtk-3.0/* "$GTK3_DIR/"
+
+	# Apply GNOME theme settings
+	echo "Applying GNOME settings for user $user..."
+
+	# Update icon cache
+	echo "Updating icon cache for TokyoNight-Dark-Icons..."
+	gtk-update-icon-cache -f /usr/share/icons/BeautyFolders
+	gtk-update-icon-cache -f /usr/share/icons/BeautyLine
+	sleep 3
+
+	su - "$user" -c "
+        export DISPLAY=:0;
+        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$user")/bus;
+        gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors-light'
+        gsettings set org.gnome.desktop.interface icon-theme 'BeautyFolders'
+        gsettings set org.gnome.desktop.interface gtk-theme 'gnome-professional-solid-40.1-dark';
+        gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
+        gsettings set org.gnome.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
+        gsettings set org.gnome.shell.extensions.user-theme name 'Tokyonight-Dark-Theme';
+
+
+	if [ $? -eq 0 ]; then
+		echo "gnome-professional-theme applied successfully for user $user!"
+	else
+		echo "Failed to apply gnome-professional-theme. Please run 'apply-gnome-theme' manually."
+	fi
+}
 
 # Function executed before package removal
-# pre_remove() {
-#     echo "Preparing to remove the package..."
-# Example: Stop services
-# systemctl stop myservice.service
-# systemctl disable myservice.service
-# }
+pre_remove() {
+	echo "Preparing to remove gnome-professional-theme..."
+}
 
 # Function executed after package removal
-# post_remove() {
-#     echo "Cleaning up after package removal..."
-# Example: Remove data directories created by the package
-# rm -rf /var/lib/mypackage
+post_remove() {
+	echo "Restoring default GNOME settings and cleaning GTK configurations..."
 
-#     echo "If you want to remove all user data, run:"
-#     echo "rm -rf /home/*/mypackage_data"
-# }
+	# Get the username of the user running the package removal
+	user=$(logname)
+	user_home=$(getent passwd "$user" | cut -d: -f6)
+
+	if [ -z "$user_home" ]; then
+		echo "Could not determine the home directory for user $user. Skipping theme removal."
+		return
+	fi
+
+	# Directories
+	GTK4_DIR="$user_home/.config/gtk-4.0"
+	GTK3_DIR="$user_home/.config/gtk-3.0"
+
+	# Reset GNOME settings to default
+	su - "$user" -c "
+        export DISPLAY=:0;
+        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$user")/bus;
+        gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic';
+        gsettings set org.gnome.desktop.interface icon-theme 'bigicons-papient-dark';
+        gsettings set org.gnome.shell.extensions.user-theme name 'Big-Blue';
+        gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark';
+        gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
+        gsettings set org.gnome.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
+    "
+	# Update icon cache
+	echo "Updating icon cache for TokyoNight-Dark-Icons..."
+	gtk-update-icon-cache -f /usr/share/icons/bigicons-papient-dark
+
+	# Remove GTK configurations
+	if [ -d "$GTK4_DIR" ]; then
+		echo "Removing GTK 4 configuration..."
+		rm -rf "$GTK4_DIR"
+	fi
+	if [ -d "$GTK3_DIR" ]; then
+		echo "Removing GTK 3 configuration..."
+		rm -rf "$GTK3_DIR"
+	fi
+
+	if [ -d "$BACKUP_DIR" ]; then
+		echo "Restoring GTK configurations from backup..."
+
+		for backup_file in "$BACKUP_DIR"/*.tar.gz; do
+			if [[ "$backup_file" =~ gtk-4.0 ]]; then
+				echo "Restoring GTK 4 configuration from $backup_file..."
+				mkdir -p "$GTK4_DIR"
+				tar -xzf "$backup_file" -C "$(dirname "$GTK4_DIR")"
+			elif [[ "$backup_file" =~ gtk-3.0 ]]; then
+				echo "Restoring GTK 3 configuration from $backup_file..."
+				mkdir -p "$GTK3_DIR"
+				tar -xzf "$backup_file" -C "$(dirname "$GTK3_DIR")"
+			fi
+		done
+	else
+		echo "No backup directory found. Skipping restoration."
+	fi
+
+	echo "Default GNOME settings restored and GTK configurations cleaned."
+}
