build-package new release: dom 29 dez 2024 02:11:53 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -30,155 +30,246 @@
 #  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ##############################################################################
 
-# Function executed before package installation
-pre_install() {
-  echo "Preparing to install gnome-professional-theme"
+# Get the username of the user running the package installation
+declare -g pkgname='chili-gnome-professional-theme'
+declare -g user=$(logname)
+declare -g user_home=$(getent passwd "$user" | cut -d: -f6)
+declare -G DE='cinnamon'
+
+# Directories
+declare -g GTK3_DIR="$user_home/.config/gtk-3.0"
+declare -g GTK4_DIR="$user_home/.config/gtk-4.0"
+declare -g THEMES_DIR="/usr/share/themes"
+declare -g BACKUP_DIR="$user_home/$pkgname.backup-settings"
+declare -g backup_file="$BACKUP_DIR/$pkgname-settings-backup.txt"
+
+#echo "user      - $user"
+#echo "user_home - $user_home"
+#echo "pkgname   - $pkgname"
+
+export TERM=${TERM:-xterm}
+export TERM=${TERM:-xterm-256color}
+
+#Definindo variáveis de cores
+export red="\033[01;31m"
+export green="\033[01;32m"
+export yellow="\033[01;33m"
+export blue="\033[01;34m"
+export pink="\033[01;35m"
+export cyan="\033[01;36m"
+export reset="\033[0m"
+alias ls='ls -lha --color=auto'
+alias dir='ls -lha --color=auto'
+
+die() {
+	local msg="$1"
+	msg="$(sed 's/<[^>]*>//g' <<<"$msg")" # Remove as tags HTML
+	echo -e "=>${cyan}error: ${red}${msg}${reset}"
+	exit 1
 }
+export -f die
 
-# Function executed after package installation
-post_install() {
-	echo "Applying gnome-professional-theme GNOME and configuring GTK..."
+msg_raw() {
+	local msg="$1"
+	# Remove tags HTML, se existirem
+	#msg="$(sed 's/<[^>]*>//g' <<< "$msg")"
 
-	# Get the username of the user running the package installation
-	user=$(logname)
-	user_home=$(getent passwd "$user" | cut -d: -f6)
+	# Verifica se existe ':' na mensagem
+	if [[ "$msg" == *:* ]]; then
+		# Divide a string antes e depois do primeiro ':'
+		local before_colon="${msg%%:*}:"
+		local after_colon="${msg#*: }"
+		# Aplica as cores
+		msg="${cyan}${before_colon} ${red}${after_colon}${reset}"
+	else
+		# Se não houver ':', aplica apenas a cor padrão
+		msg="${cyan}${msg}${reset}"
+	fi
+	echo -e "$msg"
+}
+export -f msg_raw
 
-	if [ -z "$user_home" ]; then
-		echo "Could not determine the home directory for user $user. Skipping theme application."
-		return
+msg() {
+	local msg="$1"
+	echo -e "=>${cyan}running: ${yellow}${msg}${reset}"
+}
+export -f msg
+
+msg_ok() {
+	local msg="$1"
+	echo -e "=>${cyan}done: ${green}${msg}${reset}"
+}
+export -f msg_ok
+
+msg_run() {
+	local msg="$1"
+	echo -e "=>${cyan}running: ${yellow}${msg}${reset}"
+	eval "$msg"
+}
+export -f msg_run
+
+msg_info() {
+	local msg="$1"
+	echo -e "=>${yellow}info   : ${cyan}${msg}${reset}"
+}
+export -f msg_info
+
+msg_warning() {
+	local msg="$1"
+	echo -e "=>${red}warning: ${orange}${msg}${reset}"
+}
+export -f msg_warning
+
+replicate() {
+	local char=${1:-'#'}
+	local nsize=${2:-$(tput cols)}
+	local line
+	printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
+}
+export -f replicate
+
+# Função wrapper para executar comandos como o usuário atual
+run_as_user() {
+	local command="$1"
+
+	# Verifica se o comando foi fornecido
+	if [ -z "$command" ]; then
+		die "Erro: é necessário fornecer o comando a ser executado."
+		return 1
 	fi
 
-	# Directories
-	GTK4_DIR="$user_home/.config/gtk-4.0"
-	GTK3_DIR="$user_home/.config/gtk-3.0"
-	THEMES_DIR="/usr/share/themes"
-	BACKUP_DIR="$user_home/backup_customizations"
+	# Executa o comando como o usuário atual
+	sudo -u "$user" bash -c "$command"
+}
+export -f run_as_user
+
+################################################################################################
+
+pre_install() {
+	msg_info "Preparing to install Theme for ${DE^^}"
+}
+
+post_install() {
+	msg "Applying Theme and configuring GTK..."
+
+	if [ -z "$user_home" ]; then
+		msg_warning "Could not determine the home directory for user $user. Skipping theme application."
+		return 1
+	fi
 
 	# Backup function
 	backup_directory() {
 		local dir="$1"
 		local backup_path="$BACKUP_DIR/$(basename "$dir")-$(date +%Y%m%d%H%M%S).tar.gz"
 
-		mkdir -p "$BACKUP_DIR"
-		if [ -d "$dir" ]; then
-			echo "Backing up $dir to $backup_path"
-			tar -czf "$backup_path" -C "$(dirname "$dir")" "$(basename "$dir")"
-		else
-			echo "Directory $dir does not exist. Skipping backup."
-		fi
+		msg "Syncing $dir to $BACKUP_DIR"
+		run_as_user "rsync -Crazp $dir $BACKUP_DIR/.config/"
+		#msg "Backing Up $dir to $BACKUP_DIR"
+		#run_as_user "tar -czf $backup_path -C $(dirname "$dir") $(basename "$dir")"
 	}
+  run_as_user "mkdir -p $BACKUP_DIR"
+	backup_directory "$GTK3_DIR"
+	backup_directory "$GTK4_DIR"
 
-	# Backup and update GTK 4 configuration
-	if [ -d "$GTK4_DIR" ]; then
-		echo "Directory $GTK4_DIR already exists. Backing up..."
-		backup_directory "$GTK4_DIR"
-	else
-		echo "Directory $GTK4_DIR not found. Creating..."
-		mkdir -p "$GTK4_DIR"
+	msg "Backing up current settings to $backup_file..."
+	run_as_user "
+    {
+      echo org.$DE.desktop.interface cursor-theme \$(gsettings get org.$DE.desktop.interface cursor-theme);
+      echo org.$DE.desktop.interface icon-theme \$(gsettings get org.$DE.desktop.interface icon-theme);
+      echo org.$DE.desktop.interface gtk-theme \$(gsettings get org.$DE.desktop.interface gtk-theme);
+      echo org.$DE.desktop.background picture-uri \$(gsettings get org.$DE.desktop.background picture-uri);
+      if [ \"$DE\" != \"cinnamon\" ]; then
+        echo org.$DE.desktop.background picture-uri-dark \$(gsettings get org.$DE.desktop.background picture-uri-dark);
+        echo org.$DE.shell.extensions.user-theme name \$(gsettings get org.$DE.shell.extensions.user-theme name);
+      fi
+    } > \"$backup_file\"
+  "
+
+	msg_info "Applying settings for user $user..."
+	msg "Copying theme GTK files to $GTK3_DIR/"
+	run_as_user "mkdir -p $GTK3_DIR"
+	run_as_user "cp -Rpa $THEMES_DIR/gnome-professional-solid-40.1-dark/gtk-3.0/* $GTK3_DIR/"
+
+	msg "Copying theme GTK files to $GTK4_DIR/"
+	run_as_user "mkdir -p $GTK4_DIR"
+	run_as_user "cp -Rpa $THEMES_DIR/gnome-professional-solid-40.1-dark/gtk-4.0/* $GTK4_DIR/"
+
+	msg "Updating icon cache..."
+	gtk-update-icon-cache -f /usr/share/icons/BeautyFolders 2>/dev/null
+	gtk-update-icon-cache -f /usr/share/icons/BeautyLine 2>/dev/null
+	sleep 2
+
+	# Cria um comando adicional baseado na condição
+	extra_commands=""
+	if [ "$DE" != "cinnamon" ]; then
+		extra_commands+="gsettings set org.$DE.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'; "
+		extra_commands+="gsettings set org.$DE.shell.extensions.user-theme name 'Tokyonight-Dark-Theme'; "
 	fi
-	cp -rp $THEMES_DIR/Tokyonight-Dark-Theme/gtk-4.0/* "$GTK4_DIR/"
 
-	# Backup and update GTK 3 configuration
-	if [ -d "$GTK3_DIR" ]; then
-		echo "Directory $GTK3_DIR already exists. Backing up..."
-		backup_directory "$GTK3_DIR"
-	else
-		echo "Directory $GTK3_DIR not found. Creating..."
-		mkdir -p "$GTK3_DIR"
-	fi
-	cp -rp $THEMES_DIR/Tokyonight-Dark-Theme/gtk-3.0/* "$GTK3_DIR/"
-
-	# Apply GNOME theme settings
-	echo "Applying GNOME settings for user $user..."
-
-	# Update icon cache
-	echo "Updating icon cache for TokyoNight-Dark-Icons..."
-	gtk-update-icon-cache -f /usr/share/icons/BeautyFolders
-	gtk-update-icon-cache -f /usr/share/icons/BeautyLine
-	sleep 3
-
-	su - "$user" -c "
-        export DISPLAY=:0;
-        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$user")/bus;
-        gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors-light'
-        gsettings set org.gnome.desktop.interface icon-theme 'BeautyFolders'
-        gsettings set org.gnome.desktop.interface gtk-theme 'gnome-professional-solid-40.1-dark';
-        gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
-        gsettings set org.gnome.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
-        gsettings set org.gnome.shell.extensions.user-theme name 'Tokyonight-Dark-Theme';
-
+	# Executa o comando
+	run_as_user "
+    export DISPLAY=:0; \
+    export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $user)/bus; \
+    gsettings set org.$DE.desktop.interface cursor-theme 'capitaine-cursors-light'; \
+    gsettings set org.$DE.desktop.interface icon-theme 'BeautyFolders'; \
+    gsettings set org.$DE.desktop.interface gtk-theme 'gnome-professional-solid-40.1-dark'; \
+    gsettings set org.$DE.desktop.background picture-uri 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'; \
+    $extra_commands
+  "
 
 	if [ $? -eq 0 ]; then
-		echo "gnome-professional-theme applied successfully for user $user!"
+		replicate '-'
+		msg_ok "Theme applied successfully for user $user!"
+		replicate '-'
 	else
-		echo "Failed to apply gnome-professional-theme. Please run 'apply-gnome-theme' manually."
+		replicate '-'
+		msg_warning "Failed to apply Theme. Please run 'apply-gnome-theme' manually."
+		replicate '-'
 	fi
 }
 
 # Function executed before package removal
 pre_remove() {
-	echo "Preparing to remove gnome-professional-theme..."
+	msg_info "Preparing to remove Theme for ${DE^^}..."
 }
 
 # Function executed after package removal
 post_remove() {
-	echo "Restoring default GNOME settings and cleaning GTK configurations..."
+	msg_info "Restoring default settings and cleaning GTK configurations..."
 
-	# Get the username of the user running the package removal
-	user=$(logname)
-	user_home=$(getent passwd "$user" | cut -d: -f6)
-
-	if [ -z "$user_home" ]; then
-		echo "Could not determine the home directory for user $user. Skipping theme removal."
-		return
+	if [[ -z "$user_home" ]]; then
+		die "Could not determine the home directory for user $user. Skipping theme removal."
+		return 1
 	fi
 
-	# Directories
-	GTK4_DIR="$user_home/.config/gtk-4.0"
-	GTK3_DIR="$user_home/.config/gtk-3.0"
+	if [[ -f "$backup_file" ]]; then
+		msg "Restoring GNOME settings from $backup_file..."
+		while IFS= read -r line; do
+			schema=$(echo "$line" | awk '{print $1}')
+			key=$(echo "$line" | awk '{print $2}')
+			value=$(echo "$line" | cut -d' ' -f3-)
 
-	# Reset GNOME settings to default
-	su - "$user" -c "
-        export DISPLAY=:0;
-        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$user")/bus;
-        gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic';
-        gsettings set org.gnome.desktop.interface icon-theme 'bigicons-papient-dark';
-        gsettings set org.gnome.shell.extensions.user-theme name 'Big-Blue';
-        gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark';
-        gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
-        gsettings set org.gnome.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/chililinux/animal-painting2.jpg'
-    "
-	# Update icon cache
-	echo "Updating icon cache for TokyoNight-Dark-Icons..."
-	gtk-update-icon-cache -f /usr/share/icons/bigicons-papient-dark
-
-	# Remove GTK configurations
-	if [ -d "$GTK4_DIR" ]; then
-		echo "Removing GTK 4 configuration..."
-		rm -rf "$GTK4_DIR"
-	fi
-	if [ -d "$GTK3_DIR" ]; then
-		echo "Removing GTK 3 configuration..."
-		rm -rf "$GTK3_DIR"
-	fi
-
-	if [ -d "$BACKUP_DIR" ]; then
-		echo "Restoring GTK configurations from backup..."
-
-		for backup_file in "$BACKUP_DIR"/*.tar.gz; do
-			if [[ "$backup_file" =~ gtk-4.0 ]]; then
-				echo "Restoring GTK 4 configuration from $backup_file..."
-				mkdir -p "$GTK4_DIR"
-				tar -xzf "$backup_file" -C "$(dirname "$GTK4_DIR")"
-			elif [[ "$backup_file" =~ gtk-3.0 ]]; then
-				echo "Restoring GTK 3 configuration from $backup_file..."
-				mkdir -p "$GTK3_DIR"
-				tar -xzf "$backup_file" -C "$(dirname "$GTK3_DIR")"
-			fi
-		done
+      run_as_user "
+        export DISPLAY=:0; \
+        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$user")/bus; \
+        gsettings set $schema $key $value
+      "
+		done <"$backup_file"
+		rm "$backup_file"
 	else
-		echo "No backup directory found. Skipping restoration."
+		msg_warning "No settings backup file found. Skipping restoration."
 	fi
 
-	echo "Default GNOME settings restored and GTK configurations cleaned."
+	msg_info "Restoring GTK configurations..."
+	run_as_user "rsync -Crazp $BACKUP_DIR/./config/gtk-3.0 $GTK3_DIR/"
+	run_as_user "rsync -Crazp $BACKUP_DIR/./config/gtk-4.0 $GTK4_DIR/"
+	msg_info "Default GNOME settings restored."
+}
+
+pre_upgrade() {
+	pre_install
+}
+
+post_upgrade() {
+	post_install
 }
